spring.application.name=ChoreMonkey
spring.datasource.url=jdbc:postgresql://localhost:5432/ChoreMonkey
spring.datasource.username=postgres
spring.datasource.password=13112001dm
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.thymeleaf.cache=false

